apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hw-cert-automation
  janus-idp.io/tekton: hw-cert-automation
  backstage.io/kubernetes-id: hw-cert-automation
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hw-cert-automation
resources:
- deployment.yaml
- route.yaml
- service.yaml
